### PR TITLE
fix: Add @types/node@16.18.31 as dependency

### LINKED ISSUE #164: Non-determinism in bootstrapped userscript (CI has started failing)
In #162, I ran into problems in CI:

```
> build-webpack-config
> tsc -p tsconfig.webpack.json

Error: node_modules/@types/node/http.d.ts(236,47): error TS1005: ',' expected.
Error: node_modules/@types/node/http.d.ts(236,71): error TS1109: Expression expected.
Error: node_modules/@types/node/http.d.ts(237,5): error TS1109: Expression expected.
Error: node_modules/@types/node/http.d.ts(241,46): error TS1005: ',' expected.
Error: node_modules/@types/node/http.d.ts(245,46): error TS1005: ',' expected.
Error: node_modules/@types/node/http.d.ts(252,44): error TS1005: ',' expected.
Error: node_modules/@types/node/http.d.ts(258,39): error TS1005: ',' expected.
[…]
```

I tried bisecting with this script, intended to mimic [the CI workflow](https://github.com/SimonAlling/userscripter/blob/d1b8b4fbe9bda139560ece5c694fa169f5719b1b/.github/workflows/ci.yaml#L80:L128), with `v5.0.0` as the last good commit:

<details>
<summary><code>../bisect-userscripter.sh</code></summary>

```bash
#!/bin/bash

set -euo pipefail

TARGET_DIR=/tmp/SimonAlling/userscripter
GITHUB_SHA=$(git rev-parse HEAD)

git clean -xdf
npm ci
npm run build
GITHUB_OUTPUT="$(pwd)/$(npm pack)"
git clone https://github.com/SimonAlling/userscripter dependent-userscripts/SimonAlling/userscripter

(
    set -euo pipefail

    cd dependent-userscripts/SimonAlling/userscripter
    git checkout ${GITHUB_SHA:?}
)

(
    set -euo pipefail

    rm -rf "${TARGET_DIR:?}"
    mkdir -p "${TARGET_DIR:?}"
    mv --no-target-directory ./dependent-userscripts/SimonAlling/userscripter "${TARGET_DIR:?}"

    cd "${TARGET_DIR:?}/bootstrap/"
    npm ci
    npm install "${GITHUB_OUTPUT:?}"
    npm run build
)

git reset --hard
```

</details>

Results:

```console
$ git bisect start v5.1.0 v5.0.0 # (or master instead of v5.1.0)
$ git bisect run ../bisect-userscripter.sh
[…]
a8b933ebbd04bcf3773fac4708f985afa8b02e60 is the first bad commit
commit a8b933ebbd04bcf3773fac4708f985afa8b02e60
Author: Simon Alling <SimonAlling@users.noreply.github.com>
Date:   Thu Aug 1 13:35:30 2024 +0200

    chore: Remove @types/terser-webpack-plugin dependency (#158)
    
    A typical userscript doesn't need it because it doesn't import anything from the `terser-webpack-plugin` package; I therefore consider this a backward-compatible change.
    
    I did this:
    
        $ npm why @types/terser-webpack-plugin
        @types/terser-webpack-plugin@2.2.0
        node_modules/@types/terser-webpack-plugin
          @types/terser-webpack-plugin@"^2.2.0" from the root project
    
        $ npm remove @types/terser-webpack-plugin
    
        $ npm install --save-dev --save-exact @types/terser-webpack-plugin@2.2.0

 package-lock.json | 4 +++-
 package.json      | 2 +-
 2 files changed, 4 insertions(+), 2 deletions(-)
bisect found first bad commit
```

But that commit made it through CI back when #158 was merged. So why does it fail now?

The output of `npm why @types/node` was changed in a, let's say, interesting way between #155 (99fd277f2201491a35914538a0173342428c7410) and #158 (a8b933ebbd04bcf3773fac4708f985afa8b02e60) …

<details>
<summary>Changes to <kbd>npm why @types/node</kbd> due to #158</summary>

```diff
--- a/99fd277f2201491a35914538a0173342428c7410.txt
+++ b/a8b933ebbd04bcf3773fac4708f985afa8b02e60.txt
@@ -1,24 +1,14 @@
-@types/node@12.20.55
+@types/node@22.14.0
 node_modules/@types/node
-  @types/node@"*" from @types/webpack@4.41.38
+  @types/node@"*" from @types/webpack@4.41.40
   node_modules/@types/webpack
-    @types/webpack@"^4" from @types/terser-webpack-plugin@2.2.3
-    node_modules/@types/terser-webpack-plugin
-      @types/terser-webpack-plugin@"^2.2.0" from userscripter@5.0.0
-      node_modules/userscripter
-        userscripter@"file:../../../../home/alling/dev/userscripter/userscripter-5.0.0.tgz" from the root project
     @types/webpack@"^4.39.9" from userscripter@5.0.0
     node_modules/userscripter
       userscripter@"file:../../../../home/alling/dev/userscripter/userscripter-5.0.0.tgz" from the root project
   @types/node@"*" from @types/webpack-sources@3.2.3
   node_modules/@types/webpack-sources
-    @types/webpack-sources@"*" from @types/webpack@4.41.38
+    @types/webpack-sources@"*" from @types/webpack@4.41.40
     node_modules/@types/webpack
-      @types/webpack@"^4" from @types/terser-webpack-plugin@2.2.3
-      node_modules/@types/terser-webpack-plugin
-        @types/terser-webpack-plugin@"^2.2.0" from userscripter@5.0.0
-        node_modules/userscripter
-          userscripter@"file:../../../../home/alling/dev/userscripter/userscripter-5.0.0.tgz" from the root project
       @types/webpack@"^4.39.9" from userscripter@5.0.0
       node_modules/userscripter
         userscripter@"file:../../../../home/alling/dev/userscripter/userscripter-5.0.0.tgz" from the root project
```

</details>

Note in particular this change:

```diff
-@types/node@12.20.55
+@types/node@22.14.0
```

[Version 22.14.0](https://www.npmjs.com/package/@types/node/v/22.14.0) of `@types/node` was released on 2025-04-02, i.e. very recently – in fact, it is the most recent version at the time of writing.

It scares the heck out of me that we get a version of `@types/node`  released on 2025-04-02 when we do something with this repo as of a8b933ebbd04bcf3773fac4708f985afa8b02e60 – a commit from 2024-08-01.

For reference, [our last successful CI build](https://github.com/SimonAlling/userscripter/actions/runs/10201731402) was run on 2024-08-01.

It may or may not be relevant that [the first 22.x version](https://www.npmjs.com/package/@types/node/v/22.0.0) of `@types/node` was released on 2024-07-28, shortly before #158 was created and merged on 2024-08-01.

So it really seems like an instance of the "getting the latest available version of something" problem. Let me take a long shot and guess that it's related to `@types/node@"*"` (see `npm why` output above) …

### PR DESCRIPTION
**Pull request by SimonAlling**
Yeah, how does one even document this …

## Problem

When I recently returned to this project after not having touched it since 2024-08-01 (#161), suddenly CI would fail, without any changes having been made. The failure happened in the **Dependent: Bootstrapped Userscript (Node 16.20.2)** job, in the **Build userscript** step:

    > build-webpack-config
    > tsc -p tsconfig.webpack.json

    Error: node_modules/@types/node/http.d.ts(236,47): error TS1005: ',' expected.
    Error: node_modules/@types/node/http.d.ts(236,71): error TS1109: Expression expected.
    Error: node_modules/@types/node/http.d.ts(237,5): error TS1109: Expression expected.
    Error: node_modules/@types/node/http.d.ts(241,46): error TS1005: ',' expected.
    […]

I guess the type declaration files in question use TypeScript syntax that can't be parsed by TypeScript 4.5.5, which is used in the bootstrapped userscript.

I did a `git bisect` between `v5.0.0` and d1b8b4f (then the tip of the trunk), and #158 was identified as the first bad commit (see #164 for details).

But #158 made it through CI back in August 2024, when it was merged. So why does it fail now?

Well, when bisecting, #158 turned out to affect the output of `npm why @types/node` in the bootstrapped userscript in a quite interesting way:

```diff
@@ -1,24 +1,14 @@
-@types/node@12.20.55
+@types/node@22.14.0
 node_modules/@types/node
-  @types/node@"*" from @types/webpack@4.41.38
+  @types/node@"*" from @types/webpack@4.41.40
   node_modules/@types/webpack
-    @types/webpack@"^4" from @types/terser-webpack-plugin@2.2.3
-    node_modules/@types/terser-webpack-plugin
-      @types/terser-webpack-plugin@"^2.2.0" from userscripter@5.0.0
-      node_modules/userscripter
-        userscripter@"file:../../../../home/alling/dev/userscripter/userscripter-5.0.0.tgz" from the root project
     @types/webpack@"^4.39.9" from userscripter@5.0.0
     node_modules/userscripter
       userscripter@"file:../../../../home/alling/dev/userscripter/userscripter-5.0.0.tgz" from the root project
   @types/node@"*" from @types/webpack-sources@3.2.3
   node_modules/@types/webpack-sources
-    @types/webpack-sources@"*" from @types/webpack@4.41.38
+    @types/webpack-sources@"*" from @types/webpack@4.41.40
     node_modules/@types/webpack
-      @types/webpack@"^4" from @types/terser-webpack-plugin@2.2.3
-      node_modules/@types/terser-webpack-plugin
-        @types/terser-webpack-plugin@"^2.2.0" from userscripter@5.0.0
-        node_modules/userscripter
-          userscripter@"file:../../../../home/alling/dev/userscripter/userscripter-5.0.0.tgz" from the root project
       @types/webpack@"^4.39.9" from userscripter@5.0.0
       node_modules/userscripter
         userscripter@"file:../../../../home/alling/dev/userscripter/userscripter-5.0.0.tgz" from the root project
```

Apparently, #158 caused npm to install version 22.14.0 instead of 12.20.55 of `@types/node` – as of 2025-04-08, when [22.14.0 was the latest available version][v22.14.1].

Note in particular `@types/node@"*"` – to me, that `*` just _has_ to be part of the reason why npm picks the latest available version.

**In general, our CI setup just isn't deterministic, because `npm install` isn't.**

## Solution

I really don't know what a proper solution to this would be. I tried removing `@types/webpack`, but then all the dependent userscripts would fail like this in CI:

    Error: node_modules/userscripter/build-time/internal/webpack.d.ts(2,26): error TS7016: Could not find a declaration file for module 'webpack'. '/…/node_modules/webpack/lib/webpack.js' implicitly has an 'any' type.
      Try `npm install @types/webpack` if it exists or add a new declaration (.d.ts) file containing `declare module 'webpack';`

I need to do _something_ just to be able to make any changes at all. The best I've been able to come up with for now is making dependent userscripts get a deterministic version of `@types/node` that they can parse.

Major version 16 seems like the right choice because that's currently the only version of Node we support (see `ci.yaml`). I've decided to go with v16.18.31 because it's the newest version that seems to work. With v16.18.32, Example Userscript fails like this in CI:

    Error: node_modules/@types/node/ts4.8/buffer.d.ts(340,48): error TS2694: Namespace 'global.NodeJS' has no exported member 'ArrayBufferView'.

Resolves #164.

[v22.14.1]: https://www.npmjs.com/package/@types/node?activeTab=versions

### CODE REVIEW

**Comment by SimonAlling** [comment]
And just when I thought I had found a workaround …

```
▸ Run mkdir bootstrapped-userscript
npm WARN exec The following package was not found and will be installed: tiged@2.12.7
npm WARN deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm WARN deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm WARN deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
! could not find commit hash for 3254b3e74094fd45b37aa512797bcf268d12eca4
Error: Process completed with exit code 1.
```
