### ISSUE TITLE
Non-determinism in bootstrapped userscript (CI has started failing)

### ISSUE THREAD

**Issue by SimonAlling** [SimonAlling/userscripter#164]
In #162, I ran into problems in CI:

```
> build-webpack-config
> tsc -p tsconfig.webpack.json

Error: node_modules/@types/node/http.d.ts(236,47): error TS1005: ',' expected.
Error: node_modules/@types/node/http.d.ts(236,71): error TS1109: Expression expected.
Error: node_modules/@types/node/http.d.ts(237,5): error TS1109: Expression expected.
Error: node_modules/@types/node/http.d.ts(241,46): error TS1005: ',' expected.
Error: node_modules/@types/node/http.d.ts(245,46): error TS1005: ',' expected.
Error: node_modules/@types/node/http.d.ts(252,44): error TS1005: ',' expected.
Error: node_modules/@types/node/http.d.ts(258,39): error TS1005: ',' expected.
[…]
```

I tried bisecting with this script, intended to mimic [the CI workflow](https://github.com/SimonAlling/userscripter/blob/d1b8b4fbe9bda139560ece5c694fa169f5719b1b/.github/workflows/ci.yaml#L80:L128), with `v5.0.0` as the last good commit:

<details>
<summary><code>../bisect-userscripter.sh</code></summary>

```bash
#!/bin/bash

set -euo pipefail

TARGET_DIR=/tmp/SimonAlling/userscripter
GITHUB_SHA=$(git rev-parse HEAD)

git clean -xdf
npm ci
npm run build
GITHUB_OUTPUT="$(pwd)/$(npm pack)"
git clone https://github.com/SimonAlling/userscripter dependent-userscripts/SimonAlling/userscripter

(
    set -euo pipefail

    cd dependent-userscripts/SimonAlling/userscripter
    git checkout ${GITHUB_SHA:?}
)

(
    set -euo pipefail

    rm -rf "${TARGET_DIR:?}"
    mkdir -p "${TARGET_DIR:?}"
    mv --no-target-directory ./dependent-userscripts/SimonAlling/userscripter "${TARGET_DIR:?}"

    cd "${TARGET_DIR:?}/bootstrap/"
    npm ci
    npm install "${GITHUB_OUTPUT:?}"
    npm run build
)

git reset --hard
```

</details>

Results:

```console
$ git bisect start v5.1.0 v5.0.0 # (or master instead of v5.1.0)
$ git bisect run ../bisect-userscripter.sh
[…]
a8b933ebbd04bcf3773fac4708f985afa8b02e60 is the first bad commit
commit a8b933ebbd04bcf3773fac4708f985afa8b02e60
Author: Simon Alling <SimonAlling@users.noreply.github.com>
Date:   Thu Aug 1 13:35:30 2024 +0200

    chore: Remove @types/terser-webpack-plugin dependency (#158)
    
    A typical userscript doesn't need it because it doesn't import anything from the `terser-webpack-plugin` package; I therefore consider this a backward-compatible change.
    
    I did this:
    
        $ npm why @types/terser-webpack-plugin
        @types/terser-webpack-plugin@2.2.0
        node_modules/@types/terser-webpack-plugin
          @types/terser-webpack-plugin@"^2.2.0" from the root project
    
        $ npm remove @types/terser-webpack-plugin
    
        $ npm install --save-dev --save-exact @types/terser-webpack-plugin@2.2.0

 package-lock.json | 4 +++-
 package.json      | 2 +-
 2 files changed, 4 insertions(+), 2 deletions(-)
bisect found first bad commit
```

But that commit made it through CI back when #158 was merged. So why does it fail now?

The output of `npm why @types/node` was changed in a, let's say, interesting way between #155 (99fd277f2201491a35914538a0173342428c7410) and #158 (a8b933ebbd04bcf3773fac4708f985afa8b02e60) …

<details>
<summary>Changes to <kbd>npm why @types/node</kbd> due to #158</summary>

```diff
--- a/99fd277f2201491a35914538a0173342428c7410.txt
+++ b/a8b933ebbd04bcf3773fac4708f985afa8b02e60.txt
@@ -1,24 +1,14 @@
-@types/node@12.20.55
+@types/node@22.14.0
 node_modules/@types/node
-  @types/node@"*" from @types/webpack@4.41.38
+  @types/node@"*" from @types/webpack@4.41.40
   node_modules/@types/webpack
-    @types/webpack@"^4" from @types/terser-webpack-plugin@2.2.3
-    node_modules/@types/terser-webpack-plugin
-      @types/terser-webpack-plugin@"^2.2.0" from userscripter@5.0.0
-      node_modules/userscripter
-        userscripter@"file:../../../../home/alling/dev/userscripter/userscripter-5.0.0.tgz" from the root project
     @types/webpack@"^4.39.9" from userscripter@5.0.0
     node_modules/userscripter
       userscripter@"file:../../../../home/alling/dev/userscripter/userscripter-5.0.0.tgz" from the root project
   @types/node@"*" from @types/webpack-sources@3.2.3
   node_modules/@types/webpack-sources
-    @types/webpack-sources@"*" from @types/webpack@4.41.38
+    @types/webpack-sources@"*" from @types/webpack@4.41.40
     node_modules/@types/webpack
-      @types/webpack@"^4" from @types/terser-webpack-plugin@2.2.3
-      node_modules/@types/terser-webpack-plugin
-        @types/terser-webpack-plugin@"^2.2.0" from userscripter@5.0.0
-        node_modules/userscripter
-          userscripter@"file:../../../../home/alling/dev/userscripter/userscripter-5.0.0.tgz" from the root project
       @types/webpack@"^4.39.9" from userscripter@5.0.0
       node_modules/userscripter
         userscripter@"file:../../../../home/alling/dev/userscripter/userscripter-5.0.0.tgz" from the root project
```

</details>

Note in particular this change:

```diff
-@types/node@12.20.55
+@types/node@22.14.0
```

[Version 22.14.0](https://www.npmjs.com/package/@types/node/v/22.14.0) of `@types/node` was released on 2025-04-02, i.e. very recently – in fact, it is the most recent version at the time of writing.

It scares the heck out of me that we get a version of `@types/node`  released on 2025-04-02 when we do something with this repo as of a8b933ebbd04bcf3773fac4708f985afa8b02e60 – a commit from 2024-08-01.

For reference, [our last successful CI build](https://github.com/SimonAlling/userscripter/actions/runs/10201731402) was run on 2024-08-01.

It may or may not be relevant that [the first 22.x version](https://www.npmjs.com/package/@types/node/v/22.0.0) of `@types/node` was released on 2024-07-28, shortly before #158 was created and merged on 2024-08-01.

So it really seems like an instance of the "getting the latest available version of something" problem. Let me take a long shot and guess that it's related to `@types/node@"*"` (see `npm why` output above) …

**Comment by SimonAlling** [comment]
Hmm, so not only is `@types/node` upgraded to the latest version every time the `userscripter` tarball is installed in the bootstrapped userscript: so is `@types/webpack`. Note this change in the diff above:

```diff
-  @types/node@"*" from @types/webpack@4.41.38
+  @types/node@"*" from @types/webpack@4.41.40
```

[Version 4.41.40](https://www.npmjs.com/package/@types/webpack/v/4.41.40) is indeed the latest 4.x version at the time of writing.

**Comment by SimonAlling** [comment]
Better local CI reenactment script:

```bash
#!/bin/bash

set -euo pipefail

GITHUB_SHA=$(git rev-parse HEAD)

ownerSlashName=SimonAlling/userscripter
refInRepo=${GITHUB_SHA}
pathInRepo=bootstrap/

TARGET_DIR=/tmp/${ownerSlashName}

git clean -xdf
npm ci
npm run build
GITHUB_OUTPUT="$(pwd)/$(npm pack)"
git clone https://github.com/${ownerSlashName} dependent-userscripts/${ownerSlashName}

(
    set -euo pipefail

    cd dependent-userscripts/${ownerSlashName}
    git checkout ${refInRepo}
)

(
    set -euo pipefail

    rm -rf "${TARGET_DIR}"
    mkdir -p "${TARGET_DIR}"
    mv --no-target-directory ./dependent-userscripts/${ownerSlashName} "${TARGET_DIR}"

    cd "${TARGET_DIR}/${pathInRepo}"
    npm ci
    npm install "${GITHUB_OUTPUT}"
    npm run build
)
```

**Comment by SimonAlling** [comment]
`npm install --save-exact @types/webpack@4.41.38` didn't help − same problem.

**Comment by SimonAlling** [comment]
`npm install --save-prod @types/terser-webpack-plugin@^2.2.0` does seem to fix the problem − but why?

**Comment by SimonAlling** [comment]
`npm install --save @types/node@12` (as of d1b8b4f) also fixes the problem.

**Comment by SimonAlling** [comment]
And `npm install --save-exact @types/node@16.0.0` also works, but `npm install --save @types/node@16` doesn't. So I guess some 16.x release moved to a version of TypeScript that we can't parse.

I used `git bisect` to figure out which version of `@types/node` is the first one that causes problems for us:

```bash
git checkout -b types-node-all-16.x-versions

TYPES_NODE_16_VERSIONS="16.0.0 16.0.1 16.0.2 16.0.3 16.3.0 16.3.1 16.3.2 16.3.3 16.4.0 16.4.1 16.4.2 16.4.3 16.4.4 16.4.5 16.4.6 16.4.7 16.4.8 16.4.9 16.4.10 16.4.11 16.4.12 16.4.13 16.4.14 16.6.0 16.6.1 16.6.2 16.7.0 16.7.1 16.7.2 16.7.3 16.7.4 16.7.5 16.7.6 16.7.7 16.7.8 16.7.9 16.7.10 16.7.11 16.7.12 16.7.13 16.9.0 16.9.1 16.9.2 16.9.3 16.9.4 16.9.5 16.9.6 16.10.0 16.10.1 16.10.2 16.10.3 16.10.4 16.10.5 16.10.6 16.10.7 16.10.8 16.10.9 16.11.0 16.11.1 16.11.2 16.11.3 16.11.4 16.11.5 16.11.6 16.11.7 16.11.8 16.11.9 16.11.10 16.11.11 16.11.12 16.11.13 16.11.14 16.11.15 16.11.16 16.11.17 16.11.18 16.11.19 16.11.20 16.11.21 16.11.22 16.11.23 16.11.24 16.11.25 16.11.26 16.11.27 16.11.28 16.11.29 16.11.30 16.11.31 16.11.32 16.11.33 16.11.34 16.11.35 16.11.36 16.11.37 16.11.38 16.11.39 16.11.40 16.11.41 16.11.42 16.11.43 16.11.44 16.11.45 16.11.46 16.11.47 16.11.48 16.11.49 16.11.50 16.11.51 16.11.52 16.11.53 16.11.54 16.11.55 16.11.56 16.11.57 16.11.58 16.11.59 16.11.60 16.11.61 16.11.62 16.11.63 16.11.64 16.11.65 16.11.66 16.11.67 16.11.68 16.18.0 16.18.1 16.18.2 16.18.3 16.18.4 16.18.5 16.18.6 16.18.7 16.18.8 16.18.9 16.18.10 16.18.11 16.18.12 16.18.13 16.18.14 16.18.15 16.18.16 16.18.17 16.18.18 16.18.19 16.18.20 16.18.21 16.18.22 16.18.23 16.18.24 16.18.25 16.18.26 16.18.27 16.18.28 16.18.29 16.18.30 16.18.31 16.18.32 16.18.33 16.18.34 16.18.35 16.18.36 16.18.37 16.18.38 16.18.39 16.18.40 16.18.41 16.18.42 16.18.43 16.18.44 16.18.45 16.18.46 16.18.47 16.18.48 16.18.49 16.18.50 16.18.51 16.18.52 16.18.53 16.18.54 16.18.55 16.18.56 16.18.57 16.18.58 16.18.59 16.18.60 16.18.61 16.18.62 16.18.63 16.18.64 16.18.65 16.18.66 16.18.67 16.18.68 16.18.69 16.18.70 16.18.71 16.18.72 16.18.73 16.18.74 16.18.75 16.18.76 16.18.77 16.18.78 16.18.79 16.18.80 16.18.81 16.18.82 16.18.83 16.18.84 16.18.85 16.18.86 16.18.87 16.18.88 16.18.89 16.18.90 16.18.91 16.18.92 16.18.93 16.18.94 16.18.95 16.18.96 16.18.97 16.18.98 16.18.99 16.18.100 16.18.101 16.18.102 16.18.103 16.18.104 16.18.105 16.18.106 16.18.107 16.18.108 16.18.109 16.18.110 16.18.111 16.18.112 16.18.113 16.18.114 16.18.115 16.18.116 16.18.117 16.18.118 16.18.119 16.18.120 16.18.121 16.18.122 16.18.123 16.18.124 16.18.125 16.18.126"

for v in $TYPES_NODE_16_VERSIONS; do
  npm install --save-exact @types/node@$v
  git add package*.json
  git commit -m "v$v"
done

git bisect start types-node-all-16.x-versions master
git bisect run ../userscripter-ci.sh # https://github.com/SimonAlling/userscripter/issues/164#issuecomment-2791012935
```

And `git bisect` pointed out v16.18.32 as the first bad version, but due to a different error:

```
> build-webpack-config
> tsc -p tsconfig.webpack.json

node_modules/@types/node/ts4.8/buffer.d.ts:340:48 - error TS2694: Namespace 'global.NodeJS' has no exported member 'ArrayBufferView'.

340             byteLength(string: string | NodeJS.ArrayBufferView | ArrayBuffer | SharedArrayBuffer, encoding?: BufferEncoding): number;
                                                   ~~~~~~~~~~~~~~~
```

**Comment by SimonAlling** [comment]
And suddenly I don't get any error with v16.18.32.

**Comment by SimonAlling** [comment]
Now it's apparently v16.18.84 that is the first bad version according to `git bisect`, this time with this error:

```
> userscripter@5.0.0 compile-esm
> tsc -d -p .

node_modules/@types/node/ts4.8/events.d.ts:77:43 - error TS2370: A rest parameter must be of an array type.

77                 T[K] extends unknown[] ? (...args: T[K]) => void : never
                                             ~~~~~~~~~~~~~
```
