### PR TITLE
chore: v5.1.0

### PR DESCRIPTION
**Pull request by SimonAlling**
This release makes `userscripter init` bootstrap a userscript that uses TypeScript 4.5 (#155) and webpack 4.47.0 (#159). It also makes consumers get version 16.18.31 of `@types/node` (#165).

### CODE REVIEW

**Comment by SimonAlling** [comment]
```
> build-webpack-config
> tsc -p tsconfig.webpack.json

Error: node_modules/@types/node/http.d.ts(236,47): error TS1005: ',' expected.
Error: node_modules/@types/node/http.d.ts(236,71): error TS1109: Expression expected.
Error: node_modules/@types/node/http.d.ts(237,5): error TS1109: Expression expected.
Error: node_modules/@types/node/http.d.ts(241,46): error TS1005: ',' expected.
Error: node_modules/@types/node/http.d.ts(245,46): error TS1005: ',' expected.
Error: node_modules/@types/node/http.d.ts(252,44): error TS1005: ',' expected.
Error: node_modules/@types/node/http.d.ts(258,39): error TS1005: ',' expected.
```

Is it possible that CI fails because the directory that the bootstrapped userscript ends up in is named `userscripter`?

**Comment by SimonAlling** [comment]
I tried bisecting with this script, intended to mimic [the CI workflow](https://github.com/SimonAlling/userscripter/blob/d1b8b4fbe9bda139560ece5c694fa169f5719b1b/.github/workflows/ci.yaml#L80:L128):

```bash
#!/bin/bash

set -euo pipefail

TARGET_DIR=/tmp/SimonAlling/userscripter
GITHUB_SHA=$(git rev-parse HEAD)

git clean -xdf
npm ci
npm run build
GITHUB_OUTPUT="$(pwd)/$(npm pack)"
git clone https://github.com/SimonAlling/userscripter dependent-userscripts/SimonAlling/userscripter

(
    set -euo pipefail

    cd dependent-userscripts/SimonAlling/userscripter
    git checkout ${GITHUB_SHA:?}
)

(
    set -euo pipefail

    rm -rf "${TARGET_DIR:?}"
    mkdir -p "${TARGET_DIR:?}"
    mv --no-target-directory ./dependent-userscripts/SimonAlling/userscripter "${TARGET_DIR:?}"

    cd "${TARGET_DIR:?}/bootstrap/"
    npm ci
    npm install "${GITHUB_OUTPUT:?}"
    npm run build
)

git reset --hard
```

Results:

```console
$ git bisect start v5.1.0 v5.0.0
$ git bisect run ../bisect-userscripter.sh
[…]
a8b933ebbd04bcf3773fac4708f985afa8b02e60 is the first bad commit
commit a8b933ebbd04bcf3773fac4708f985afa8b02e60
Author: Simon Alling <SimonAlling@users.noreply.github.com>
Date:   Thu Aug 1 13:35:30 2024 +0200

    chore: Remove @types/terser-webpack-plugin dependency (#158)
    
    A typical userscript doesn't need it because it doesn't import anything from the `terser-webpack-plugin` package; I therefore consider this a backward-compatible change.
    
    I did this:
    
        $ npm why @types/terser-webpack-plugin
        @types/terser-webpack-plugin@2.2.0
        node_modules/@types/terser-webpack-plugin
          @types/terser-webpack-plugin@"^2.2.0" from the root project
    
        $ npm remove @types/terser-webpack-plugin
    
        $ npm install --save-dev --save-exact @types/terser-webpack-plugin@2.2.0

 package-lock.json | 4 +++-
 package.json      | 2 +-
 2 files changed, 4 insertions(+), 2 deletions(-)
bisect found first bad commit

```

**Comment by SimonAlling** [comment]
I wonder why that problem wasn't detected in PR build validation for #158 …

**Comment by SimonAlling** [comment]
It's absolutely beyond me why #158 would have caused this problem. I must be utterly misunderstanding something very basic.

**Comment by SimonAlling** [comment]
So the output of `npm why @types/node` was changed in a, let's say, interesting way between #155 (99fd277f2201491a35914538a0173342428c7410) and #158 (a8b933ebbd04bcf3773fac4708f985afa8b02e60) …

```diff
--- a/99fd277f2201491a35914538a0173342428c7410.txt
+++ b/a8b933ebbd04bcf3773fac4708f985afa8b02e60.txt
@@ -1,24 +1,14 @@
-@types/node@12.20.55
+@types/node@22.14.0
 node_modules/@types/node
-  @types/node@"*" from @types/webpack@4.41.38
+  @types/node@"*" from @types/webpack@4.41.40
   node_modules/@types/webpack
-    @types/webpack@"^4" from @types/terser-webpack-plugin@2.2.3
-    node_modules/@types/terser-webpack-plugin
-      @types/terser-webpack-plugin@"^2.2.0" from userscripter@5.0.0
-      node_modules/userscripter
-        userscripter@"file:../../../../home/alling/dev/userscripter/userscripter-5.0.0.tgz" from the root project
     @types/webpack@"^4.39.9" from userscripter@5.0.0
     node_modules/userscripter
       userscripter@"file:../../../../home/alling/dev/userscripter/userscripter-5.0.0.tgz" from the root project
   @types/node@"*" from @types/webpack-sources@3.2.3
   node_modules/@types/webpack-sources
-    @types/webpack-sources@"*" from @types/webpack@4.41.38
+    @types/webpack-sources@"*" from @types/webpack@4.41.40
     node_modules/@types/webpack
-      @types/webpack@"^4" from @types/terser-webpack-plugin@2.2.3
-      node_modules/@types/terser-webpack-plugin
-        @types/terser-webpack-plugin@"^2.2.0" from userscripter@5.0.0
-        node_modules/userscripter
-          userscripter@"file:../../../../home/alling/dev/userscripter/userscripter-5.0.0.tgz" from the root project
       @types/webpack@"^4.39.9" from userscripter@5.0.0
       node_modules/userscripter
         userscripter@"file:../../../../home/alling/dev/userscripter/userscripter-5.0.0.tgz" from the root project
```

Note in particular this change, apparently caused by a8b933ebbd04bcf3773fac4708f985afa8b02e60:

```diff
-@types/node@12.20.55
+@types/node@22.14.0
```

[Version 22.14.0](https://www.npmjs.com/package/@types/node/v/22.14.0) of `@types/node` was released on 2025-04-02, i.e. very recently – in fact, it is the most recent version at the time of writing.

It scares the heck out of me that we get a version of `@types/node`  released on 2025-04-02 when we do something with this repo as of a8b933ebbd04bcf3773fac4708f985afa8b02e60 – a commit from 2024-08-01.

For reference, [our last successful CI build](https://github.com/SimonAlling/userscripter/actions/runs/10201731402) was run on 2024-08-01.

It may or may not be relevant that [the first 22.x version](https://www.npmjs.com/package/@types/node/v/22.0.0) of `@types/node` was released on 2024-07-28, shortly before #158 was created and merged on 2024-08-01.

So it really seems like an instance of the "getting the latest available version of something" problem. Let me take a long shot and guess that it's related to `@types/node@"*"` (see `npm why` output above) …

**Comment by SimonAlling** [comment]
I've opened #164 to deal with the non-determinism in the bootstrapped userscript.
